---

sync:
  markers:
    important: 0
    test: 1
  mappings:
    - section: 01-Demo
      material: Demo
    - section: 01-Demo/Bla
      material: Demo/Bla
    - section: 01-Demo/Bla-Legacy
      material: Demo/Bla.[test]